//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoAlert.NUnit.Integration.CoinsInformation.Services {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CoinsRepositoryTestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoinsRepositoryTestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CryptoAlert.NUnit.Integration.CoinsInformation.Services.CoinsRepositoryTestResour" +
                            "ces", typeof(CoinsRepositoryTestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {  
        ///   &quot;status&quot;:&quot;success&quot;,
        ///   &quot;data&quot;:{  
        ///      &quot;stats&quot;:{  
        ///         &quot;total&quot;:4331
        ///      },
        ///      &quot;base&quot;:{  
        ///         &quot;symbol&quot;:&quot;USD&quot;,
        ///         &quot;sign&quot;:&quot;$&quot;
        ///      },
        ///      &quot;coins&quot;:[  
        ///         {  
        ///            &quot;id&quot;:1335,
        ///            &quot;slug&quot;:&quot;bitcoin-btc&quot;,
        ///            &quot;symbol&quot;:&quot;BTC&quot;,
        ///            &quot;name&quot;:&quot;Bitcoin&quot;,
        ///            &quot;circulatingSupply&quot;:17083525,
        ///            &quot;totalSupply&quot;:17083525,
        ///            &quot;exchangeable&quot;:true,
        ///            &quot;exchangeAvailable&quot;:true,
        ///            &quot;description&quot;:&quot;Bitcoin i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AllCoinsJsonResource {
            get {
                return ResourceManager.GetString("AllCoinsJsonResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string tfh {
            get {
                return ResourceManager.GetString("tfh", resourceCulture);
            }
        }
    }
}
